name: Check Text URLs

on:
  workflow_run:
    workflows: [Check URLs]
    types:
      - completed
  workflow_dispatch:

jobs:
  extract-attributes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check text URLs and save as CSV
      run: python check-urls.py text

    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add csv/*
        git diff --quiet && git diff --staged --quiet || (git commit -m "chore: Add daily check URLs results for text RFCs" && git push)


